"""create security session

Revision ID: 3976b8c687b3
Revises: 9a5d853b93d9
Create Date: 2026-08-23 16:28:34.288383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3976b8c687b3'
down_revision: Union[str, Sequence[str], None] = '9a5d853b93d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS security")
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED', 'EXPIRED')", name='ck_session_status'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session', schema='security')
    # ### end Alembic commands ###
